- name: ansible-role-linux-postgresql
  src: git+https://github.com/goldstrike77/ansible-role-linux-postgresql
  version: origin/master

- name: ansible-role-linux-redis
  src: git+https://github.com/goldstrike77/ansible-role-linux-redis
  version: origin/master
