---
- name: Creating GitLab folder
  file:
    dest: '{{ gitlab_data_path }}/gitlab'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: GitLab main configuration file transfer
  template:
    src: 'gitlab.v{{ gitlab_version.split(".")[0] }}.rb.j2'
    dest: '/etc/gitlab/gitlab.rb'
    owner: root
    group: root
    mode: 0600
  register: conf_update

- name: GitLab configure opeations
  block:
    - name: Shutoff GitLab
      command: >
        /bin/gitlab-ctl stop
      failed_when: false
    - name: Restart GitLab Runit supervision process
      systemd:
        name: 'gitlab-runsvdir'
        enabled: 'yes'
        state: 'restarted'
      failed_when: false
    - name: Reconfigure GitLab
      command: >
        /bin/gitlab-ctl reconfigure
        creates=/var/opt/gitlab/bootstrapped
      failed_when: false
  when: conf_update is changed
