---
- name: Allow GitLab service port
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ gitlab_port_arg|dict2items }}'
